### ISSUE TITLE
Unnecessary and wrong part for Syft in tools.yaml

### ISSUE THREAD

**Issue by ataseren** [ErdemOzgen/DevSecOpsBuilder#10]
This is a code segment from tools.yaml:
```
- name: syfte
      install: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin
      update: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin
      help: syfte --help
      default: true
      language:
        - "All"
      devsecops:
        name: syfte
        description: "Syft is a CLI tool and library for generating a Software Bill of Materials (SBOM) from container images and filesystems."
        category: "scanner"
        url: https://github.com/anchore/syfte
```

This segment installs Syft tool. However, it is named as "Syfte" in some YAML values and even help command. Other than this mistype, this whole segment is unnecessary because we have another segment that installs Syft. Also, issue #4 is about that segment. By solving it, we can successfully install Syft and we can remove this false segment.
