### ISSUE TITLE
ZAP Proxy wrong help command

### ISSUE THREAD

**Issue by ataseren** [ErdemOzgen/DevSecOpsBuilder#8]
This is the code segment for installation of ZAP Proxy:
```
- name: zap-proxy #done
      install: sudo snap install zaproxy --classic
      update: sudo snap refresh zaproxy --classic
      help: zap-proxy --help
      default: true
      language:
        - "All"
      devsecops:
        name: zap-proxy
        description: "The OWASP Zed Attack Proxy (ZAP) is one of the world’s most popular free security tools and is actively maintained by hundreds of international volunteers."
        category: "DAST"
        url: https://www.zaproxy.org/download/
```

`zap-proxy --help` command is wrong. We should use `zaproxy -h` or `zaproxy -help`
